---
name: Python application test

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull python image
        run: docker pull python:3.10-slim
      - name: Build app container
        run: docker compose build daemon
      - name: Run app container
        run: docker compose up -d daemon
      # - name: Run pre-commit hooks
      #   uses: pre-commit/action@v2.0.0
      - name: Run tests
        run: docker compose run daemon python test.py
